[build-system]
requires = ["setuptools>=82.0.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mstarpy"
version = "11.0.1"
description = "Mutual funds and stocks data extraction from MorningStar with Python"
readme = "README.md"
license = { text = "MIT License" }
authors = [
    { name = "Maël Jourdain", email = "mael.jourdain@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.0",
    "requests>=2.28",
    "selenium>=4.0",
    "statsmodels>=0.14",
    "matplotlib>=3.7"
]

[tool.setuptools.packages.find]
where = ["."]